### ISSUE TITLE
Replace `screen` div by a Canvas element

### ISSUE THREAD

**Issue by piranna** [attackemartin/css-gameboy#1]
Replace the `screen` div with a Canvas element with the proper resolution. CSS filters can also be applied too force have 4-bits color depth to whatever you print there, too, and maybe something similar can be done to force have proper resolution.

**Comment by attackemartin** [comment]
hey :) you can place whatever you want into the screen div. So if you want to make it a canvas, you're free to do so.
But others maybe want to display an image, or a video.

**Comment by piranna** [comment]
Fair enought :-) Not sure if a image for example purposses would be useful. At least, definitely we should apply some SVG filters on the DIV to force the 4 bits color of the screen, it should be easy to do with quantitation + color.

**Comment by attackemartin** [comment]
as I mentioned, one can do with it whatever one will :) So if you want to apply some svg filters, you're absolutely free to do so, and I would love to see the project you're doing with it!
For this repo though, I'll let the screen container as it is, for people to alter it the way they want :)
I would close this issue for now, but I appreciate your feedback!
